language: go

go:
  - stable
  - 1.14.x

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
  - overalls -project=github.com/shootingfans/socket -covermode=count -ignore='.git,_vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -coverprofile=coverage.txt -covermode=atomic ./...
  - go test -v -test.bench=".*" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)